### ISSUE TITLE
Support load Go SDK from mise tools

### ISSUE THREAD

**Issue by 134130** [134130/intellij-mise#8]

**Comment by 134130** [comment]
Will be added on v1.2.0

**Comment by taylankasap** [comment]
How does this work? I open a go project that has a .mise.toml:

```
[tools]
go = "prefix:1.19"
```

The IDE still sets GOROOT to the latest go installed on my pc instead of go 1.19.

What I've tried so far:

1. Setting .mise.toml to

```
[tools]
go = "1.19.13"
```
2. Restarting the IDE
3. Removing the .idea directory

Note: I have 2.0.0 version of the plugin on Goland 2024.2.0.1

**Comment by 134130** [comment]
@taylankasap 

Hi!

Have you ever tried a "Realod Go SDK" action, which you can see on README.md screenshot?

**Comment by taylankasap** [comment]
Hi, I read the plugin readme on goland so I thought this readme was the same and didn't notice it. Is there a way to make this reload automatic (similar to how mise works)?

**Comment by 134130** [comment]
@taylankasap I've failed to figure out to auto-load `.mise.toml` file when GoLand open (actually no deeply researched). I'll check it again!

**Comment by 134130** [comment]
@taylankasap Hi, now you can get the v2.0.1, the patched version.
