### ISSUE TITLE
`MISE_PROFILE` got deprecated in favor of `MISE_ENV`

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#98]
Both `--profile` and `--env` are still supported, though need to at least update the link to the docs.
https://mise.jdx.dev/configuration/environments.html

By checking the version, it should be possible to also use `--env` when calling `mise` also

**Comment by 134130** [comment]
I've never noticed that.

- On Nov 10, @jdx made a [pull request](https://github.com/jdx/mise/pull/2973) that `MISE_PROFILE` is the next of `MISE_ENV`, which will deprecates it.
- But on Nov 28, @jdx made a [pull request](https://github.com/jdx/mise/pull/3235), introducing a shortcut of `mise run <task>`. 😔
  - And It contains a ninja patch which hides `MISE_PROFILE` from usage. ([files](https://github.com/jdx/mise/pull/3235/files#diff-453fee9ce49c9f812a348d5f4414f628785e1463ce4fbec4885ed9108d446a0cR34))

So that was the reason why I did not noticed that.

**Comment by 134130** [comment]
Thanks for letting me know

**Comment by hverlin** [comment]
Yeah, the main issue is the link; otherwise the change is backward compatible. Thank you for making the change!

**Comment by jdx** [comment]
to be clear, MISE_PROFILE isn't deprecated, just hidden
